# -*- coding: utf-8 -*-
"""HW3_adversarial_contrastive_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dNageD80aYS1hY9z0hq7ieZFzrwYB9xp

# Homework 3 - Adversarial Attacks and Contrastive Learning

### Submission Guidelines

- This notebook contains all the questions. You should follow the instructions below.
- Solutions for the practical parts should be written in this notebook/py (see submission files) and for the dry "theoretical" parts in a pdf report.

You should submit the following files:
- Code files - You can choose 1 of the following options:
  - IPYNB notebook including the solutions to all 4 parts. The `.ipynb` file should not include any answers to dry questions because they should all be in the PDF report. Markdown cells in the notebook will not be checked.
  - PY files: 2 `.py` files, one for questions 1-3 and one for question 4. Submission format for `.py` files -  `HW3_Partn_ID1_ID2.py` where `n=1` is for parts 1-3 and `n=2` is for part 4.

- PDF file - report:
  - Answers for all the dry parts - analysis, visualization, dry questions, embeddings. You must create a PDF report, even if you chose to implement your code using a Jupyter Notebook. The PDF should not be a PDF version of the notebook and doesn't need to include any code.

Good Luck!

Libraries that can be used in this assignment:

- PyTorch (torch, torchvision, torch.optim, torch.nn, ...) -- Any other deep learning libraries such as keras are prohibited
- NumPy
- Any libraries used for visualization
- PIL (for image processing)

For any libraries other than those listed above, you may ask in the forum.

## Theory - Neural Network Expressivity (20pt)

Solve the following exercises rigorously. Note that your proof does not need to be typed (can be handwritten), and answers should be in the PDF report (not notebook).

### 1. The necessity of continuity for supremum ($L^\infty$) approximation.
Show that the Universal Approximation Theorem does not hold for discontinuous function under the supremum norm. Specifically, provide a counter-example $f$ that satisfies:
1. $f:[0,1]\to\mathbb{R}$ is bounded and has a **finite** set of discontinuities $\mathcal{D}$, but is continuous everywhere else in $[0,1]$.
2. There does not exist a depth-2 ReLU neural network $N$ such that for every $\epsilon>0$:
$$ \sup_{[0, 1]} |f(x)-N(x)| < \epsilon. $$

*Hint: ReLU networks are continuous functions in all of $\mathbb{R}$.*

### 2. Variation of UAT using $L^1$ approximation.
Let $f:[0,1]\to\mathbb{R}$ be a bounded function with a finite set of discontinuities $\mathcal{D}$. Prove that for any $\epsilon>0$, there exists a depth-2 ReLU network $N(x)$ such that:

$$\int_0^1 |f(x)-N(x)|dx < \epsilon. $$

In other words, we replaced the $L^\infty$ norm (for which the statement isn't true from part 1) with the $L^1$ norm.

**Proof Guideline:**
1. **Step function approximation (you don't have to do anything in this step):** Since $f$ is bounded with finitely many discontinuities, $f$ is Riemann integrable on $[0,1]$ so for any $\epsilon > 0$, there exists a step function
    $$S(x) = \sum_{j=1}^{m} c_j \mathbf{1}_{(a_{j-1}, a_j)}(x)$$
    where $0 = a_0 < a_1 < \cdots < a_m = 1$, such that $|f(x)-S(x)|<\frac{\epsilon}{2}$. Therefore,

    $$ \int_0^1 |f(x) - S(x)| dx < \frac{\epsilon}{2}$$

2. **Trapezoidal construction:** Show that an indicator function $1_{x\in (a,b)}$ can be approximated using a linear combination of four ReLU units by creating a trapezoid function $T_{a,b}^\delta(x)$ which returns $1$ for $x\in[a,b]$ and $0$ for $x\notin(a-\delta, b+\delta)$. Bound the $L^1$ distance between $1_{[a,b]}(x)$ and $T_{a,b}^\delta(x)$.
3. **Network Construction:** Define the network $N(x)$ using the trapezoidal functions and $\{c_j\}_{j=1}^m$.
    - Show why $N(x)$ is a valid depth-2 ReLU network.
    - Bound the $L^1$ distance $\int_0^1 |S(x)-N(x)|\,dx$. Note that using the triangle inequality, $\int_0^1 |S(x)-N(x)\le \int_0^1 \sum_{j=1}^m |c_j||1_{[a_j,a_{j+1}]}(x) - T_{a_j, a_{j+1}}^\delta(x)|\,dx$, which we can bound by switching the sum and the integral.
    - Determine the constraints on $\delta$ required to ensure the distance is less than $\frac{\epsilon}{2}$.
4. Put everything together using the triangle inequality.

## Part 1 - Training a CNN on SVHN (5pt)

Train a classifier on the dataset SVHN (Street View House Numbers), available through ```torchvision.datasets```. The model accuracy should reach at least 90% on the test set. You're free to add as many data augmentations as necessary. Take into consideration that any serious augmentations (like normalization) should be reversed when displaying images in future sections.
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torchvision import models
from torch.utils.data import DataLoader
from tqdm import tqdm
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

mean, std = [0.4377, 0.4438, 0.4728], [0.1980, 0.2010, 0.1970]

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean, std)
])

train_set = torchvision.datasets.SVHN(root='./data', split='train', download=True, transform=transform)
test_set = torchvision.datasets.SVHN(root='./data', split='test', download=True, transform=transform)

train_loader = DataLoader(train_set, batch_size=128, shuffle=True, num_workers=2)
test_loader = DataLoader(test_set, batch_size=128, shuffle=False, num_workers=2)

model = models.resnet18(num_classes=10).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

loss_history = []
acc_history = []

def train_model(epochs=5):
    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        progress_bar = tqdm(train_loader, desc=f'Epoch {epoch+1}/{epochs}')

        for inputs, labels in progress_bar:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

            progress_bar.set_postfix(loss=running_loss/len(train_loader), acc=f"{(100.*correct/total):.2f}%")

        loss_history.append(running_loss/len(train_loader))
        acc_history.append(100. * correct / total)

if __name__ == "__main__":
    train_model(epochs=7)

    plt.figure(figsize=(10, 5))
    plt.plot(range(1, len(loss_history) + 1), loss_history, label='Training Loss', marker='o')
    plt.title('Training Loss Over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.show()

    model.eval()
    test_correct = 0
    test_total = 0
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, predicted = outputs.max(1)
            test_total += labels.size(0)
            test_correct += predicted.eq(labels).sum().item()

    print(f"\n✅ Training Finished! Final Test Accuracy: {(100.*test_correct/test_total):.2f}%")
    torch.save(model.state_dict(), "resnet18_svhn.pth")

"""### Analysis

Analyze the performance of the model on the test set (e.g. through a confusion matrix). Display at least 4 images that the model predicts incorrectly and their predicted classes. Discuss possible weaknesses of the model and their causes.
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

def imshow(img):
    img = img.cpu().numpy().transpose((1, 2, 0))
    mean = np.array([0.4377, 0.4438, 0.4728])
    std = np.array([0.1980, 0.2010, 0.1970])
    img = std * img + mean
    img = np.clip(img, 0, 1)
    return img

model.eval()
all_preds = []
all_labels = []
errors = []

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

        misclassified_mask = preds != labels
        if misclassified_mask.any():
            for i in range(len(misclassified_mask)):
                if misclassified_mask[i]:
                    errors.append({
                        'img': inputs[i],
                        'pred': preds[i].item(),
                        'label': labels[i].item()
                    })

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(10, 8))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=range(10))
disp.plot(cmap='Blues', values_format='d')
plt.title('Confusion Matrix - SVHN')
plt.show()

plt.figure(figsize=(12, 4))
for i in range(4):
    error = errors[i]
    plt.subplot(1, 4, i+1)
    plt.imshow(imshow(error['img']))
    plt.title(f"Pred: {error['pred']} | Actual: {error['label']}")
    plt.axis('off')
plt.tight_layout()
plt.show()

"""# Final Report: SVHN Digit Classification

## 1. Model Description and Methodology
In this task, a Deep Residual Network (**ResNet18**) was trained to classify street view house numbers using the SVHN dataset.

* **Architecture:** ResNet18 was selected for its use of residual skip connections, which mitigate the vanishing gradient problem and allow for efficient training of deep architectures.
* **Optimization:** The model was optimized using the **Adam** optimizer with a learning rate of $\alpha = 0.001$. **Cross-Entropy Loss** was utilized as the objective function for this multi-class classification task.
* **Augmentation & Preprocessing:** Images were normalized using the dataset-specific mean and standard deviation:
    * $\mu = [0.4377, 0.4438, 0.4728]$
    * $\sigma = [0.1980, 0.2010, 0.1970]$
    Data augmentation techniques, such as **Random Cropping**, were applied during training to improve the model's spatial invariance and generalization capabilities.

## 2. Results
The model achieved a final test accuracy of **91.51%** within 7 epochs, successfully exceeding the project requirement of 90%.

## 3. Error Analysis
An analysis of the Confusion Matrix and a review of misclassified samples revealed the following:

* **Inter-class Similarity:** The model occasionally confuses visually similar digits, such as $3$ and $9$, or $6$ and $8$. For instance, if the bottom curve of a '3' is nearly closed, the model may misidentify it as the loop of a '9'.
* **Image Quality Issues:** A significant portion of errors occurs in images characterized by **Motion Blur** or extremely low resolution. These artifacts obscure the fine details necessary to distinguish between similar digit shapes.
* **Lighting and Contrast:** In low-contrast or poorly lit images, the model struggles to effectively separate the digit from the background, leading to incorrect predictions based on partial or distorted contours.

## 4. Model Weaknesses and Causes
1.  **Sensitivity to Distractors:** The SVHN dataset often contains neighboring digits within the same frame. The model may occasionally focus on these peripheral "distractors" rather than the central digit.
2.  **Contextual Information Loss:** Due to the fixed $32 \times 32$ resolution, any imprecise cropping results in a loss of critical visual information, making classification difficult even for human observers.
3.  **Geometric Variance:** While the model is robust, it remains somewhat sensitive to extreme perspective distortions or rotations, which could be further mitigated by more aggressive geometric data augmentations.

## Part 2: Adversarial Attacks on our Model (15pt)

### Dry Question
In Slide 14 of the tutorial on adversarial attacks, we showed how attacks can be transfered from one model to another, i.e. if we craft an attack for ResNet50 using FGSM, it will likely also confuse other models. Why is this property important, specifically when attacking an unknown model?

Implement the FGSM algorithm as shown in the tutorial (it may be necessary to make require_grad be True for our input data in order to calculate its gradient). Define a function ```eval_adversarial(model, test_loader, epsilon)``` that applies FGSM on the test data by creating new images which are perturbed versions of the originals, and calculates the model's accuracy only on the perturbed images. Test accuracy after the attack should be less than 25% for $\varepsilon=0.1$.
"""

def normalize_batch(x01, mean, std, device):
    mean_t = torch.tensor(mean, device=device).view(1,3,1,1)
    std_t  = torch.tensor(std,  device=device).view(1,3,1,1)
    return (x01 - mean_t) / std_t

def denormalize_batch(xn, mean, std, device):
    mean_t = torch.tensor(mean, device=device).view(1,3,1,1)
    std_t  = torch.tensor(std,  device=device).view(1,3,1,1)
    return (xn * std_t + mean_t).clamp(0,1)

def fgsm_attack_pixelspace(model, x_norm, y, epsilon):
    """
    x_norm: normalized input from loader
    We convert to pixel space [0,1], compute grad wrt pixels, perturb in [0,1],
    then re-normalize and feed to the model.
    """
    model.eval()
    y = y.to(device)

    # back to pixel space
    x01 = denormalize_batch(x_norm.to(device), mean, std, device).detach().clone()
    x01.requires_grad_(True)

    # forward on normalized version of pixel-space tensor
    logits = model(normalize_batch(x01, mean, std, device))
    loss = criterion(logits, y)

    model.zero_grad(set_to_none=True)
    if x01.grad is not None:
        x01.grad.zero_()
    loss.backward()

    grad = x01.grad.detach()
    x01_adv = (x01 + epsilon * grad.sign()).clamp(0, 1)

    # return normalized adversarial inputs (what model expects)
    return normalize_batch(x01_adv, mean, std, device).detach()

def eval_adversarial(model, test_loader, epsilon):
    model.eval()
    correct, total = 0, 0

    for x, y in test_loader:
        x_adv = fgsm_attack_pixelspace(model, x, y, epsilon)

        with torch.no_grad():
            pred = model(x_adv).argmax(dim=1)

        y = y.to(device)
        correct += (pred == y).sum().item()
        total += y.size(0)

    return 100.0 * correct / total

acc_adv = eval_adversarial(model, test_loader, epsilon=0.1)
print(f"Adversarial test accuracy (epsilon=0.1): {acc_adv:.2f}%  (expected: < 25%)")

"""### Visualization

Visualize some images that the model got right before the perturbation and wrong after the attack. Create a confusion matrix of the output on the entire test set (looking only at the perturbed images).
"""

import matplotlib.pyplot as plt

def show_right_before_wrong_after(model, test_loader, epsilon, max_examples):
    model.eval()
    images = []
    titles = []

    for x_norm, y in test_loader:
        x_norm = x_norm.to(device)
        y = y.to(device)

        # prediction BEFORE attack
        with torch.no_grad():
            pred_clean = model(x_norm).argmax(dim=1)

        # create adversarial examples (needs gradients)
        x_adv_norm = fgsm_attack_pixelspace(model, x_norm, y, epsilon)

        # prediction AFTER attack
        with torch.no_grad():
            pred_adv = model(x_adv_norm).argmax(dim=1)

        mask = (pred_clean == y) & (pred_adv != y)
        idxs = mask.nonzero(as_tuple=False).squeeze(1).tolist()

        for i in idxs:
            if len(images) >= max_examples:
                break

            img01 = denormalize_batch(
                x_adv_norm[i:i+1], mean, std, device
            )[0].detach().cpu().permute(1, 2, 0).numpy()

            images.append(img01)
            titles.append(
                f"Clean: {pred_clean[i].item()} | "
                f"Adv: {pred_adv[i].item()} | "
                f"True: {y[i].item()}"
            )

        if len(images) >= max_examples:
            break

    if len(images) == 0:
        print("No examples found.")
        return

    # ---- plot horizontally ----
    fig, axes = plt.subplots(1, len(images), figsize=(3 * len(images), 3))

    if len(images) == 1:
        axes = [axes]

    for ax, img, title in zip(axes, images, titles):
        ax.imshow(img)
        ax.set_title(title, fontsize=9)
        ax.axis("off")

    plt.tight_layout()
    plt.show()

show_right_before_wrong_after(model, test_loader, epsilon=0.1, max_examples=5)

import torch
import matplotlib.pyplot as plt

def confusion_matrix_adversarial(model, test_loader, epsilon, num_classes=10):
    model.eval()
    cm = torch.zeros((num_classes, num_classes), dtype=torch.int64)

    for x_norm, y in test_loader:
        x_norm = x_norm.to(device)
        y = y.to(device)

        # ---- create adversarial examples (needs gradients) ----
        x_adv_norm = fgsm_attack_pixelspace(model, x_norm, y, epsilon)

        # ---- prediction only (no gradients) ----
        with torch.no_grad():
            pred = model(x_adv_norm).argmax(dim=1)

        for t, p in zip(y.view(-1), pred.view(-1)):
            cm[t.long(), p.long()] += 1

    return cm.cpu()


def plot_confusion_matrix(cm, title="Confusion Matrix (Adversarial)"):
    plt.figure(figsize=(7, 6))
    plt.imshow(cm, interpolation="nearest")
    plt.title(title)
    plt.xlabel("Predicted label")
    plt.ylabel("True label")
    plt.colorbar()
    plt.xticks(range(cm.shape[1]))
    plt.yticks(range(cm.shape[0]))

    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            if cm[i, j] > 0:
                plt.text(j, i, int(cm[i, j]), ha="center", va="center", fontsize=8)

    plt.tight_layout()
    plt.show()

cm_adv = confusion_matrix_adversarial(
    model, test_loader, epsilon=0.1, num_classes=10
)
plot_confusion_matrix(cm_adv, title="Confusion Matrix - SVHN (FGSM, epsilon=0.1)")

"""Test the function with different values of epsilon (at least 5) and plot the accuracy as a function of epsilon. For each epsilon, display the perturbed images with the model's classification. At what epsilon does it become harder for the human eye to correctly classify?"""

import matplotlib.pyplot as plt

epsilons = [0.0, 0.01, 0.02, 0.05, 0.1]  # 5 values (include 0 for baseline)
accs = []

for eps in epsilons:
    acc = eval_adversarial(model, test_loader, epsilon=eps)
    accs.append(acc)
    print(f"epsilon={eps:.2f} -> adv accuracy={acc:.2f}%")

plt.figure(figsize=(7,4))
plt.plot(epsilons, accs, marker='o')
plt.title("Adversarial Accuracy vs Epsilon (FGSM, pixel-space)")
plt.xlabel("epsilon")
plt.ylabel("accuracy (%)")
plt.grid(True)
plt.show()

import numpy as np

def show_perturbed_examples_per_epsilon(model, test_loader, epsilons, num_images=5):
    model.eval()

    # take one batch to visualize consistently across epsilons
    x_norm, y = next(iter(test_loader))
    x_norm = x_norm.to(device)
    y = y.to(device)

    # only take first num_images
    x_norm = x_norm[:num_images]
    y = y[:num_images]

    for eps in epsilons:
        # create adversarial examples
        x_adv_norm = fgsm_attack_pixelspace(model, x_norm, y, epsilon=eps)

        # predictions on adv
        with torch.no_grad():
            pred_adv = model(x_adv_norm).argmax(dim=1)

        # convert to pixel space for display
        imgs01 = denormalize_batch(x_adv_norm, mean, std, device).detach().cpu().permute(0,2,3,1).numpy()

        fig, axes = plt.subplots(1, num_images, figsize=(3*num_images, 3))
        fig.suptitle(f"FGSM perturbed images (epsilon={eps})", fontsize=14)

        if num_images == 1:
            axes = [axes]

        for i, ax in enumerate(axes):
            ax.imshow(imgs01[i])
            ax.axis("off")
            ax.set_title(f"Pred: {pred_adv[i].item()}\nTrue: {y[i].item()}", fontsize=10)

        plt.tight_layout()
        plt.show()

# run
show_perturbed_examples_per_epsilon(model, test_loader, epsilons, num_images=5)

"""## Part 3: Training our model using adversarial training (20pt)

For each point in the training data, increase the model's robustness by training not only on the point itself, but on the perturbed point after the FGSM algorithm using $\varepsilon=0.1$. Afterwards, compute the accuracy once again on the newly trained model using ```eval_adversarial(model, test_loader, epsilon)``` defined above. The accuracy **looking only at the perterubed data** should be at least 70%.
"""

import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

epsilon_train = 0.1
adv_epochs = 3
optimizer_adv = optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

def adversarial_train_epoch(model, train_loader, optimizer, criterion, epsilon, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    progress_bar = tqdm(train_loader, desc=f'Adversarial Training (eps={epsilon})')

    for inputs, labels in progress_bar:
        inputs, labels = inputs.to(device), labels.to(device)

        inputs_adv = fgsm_attack_pixelspace(model, inputs, labels, epsilon)

        optimizer.zero_grad()

        outputs_clean = model(inputs)
        outputs_adv = model(inputs_adv)

        loss = 0.5 * criterion(outputs_clean, labels) + 0.5 * criterion(outputs_adv, labels)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs_adv.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        progress_bar.set_postfix(loss=running_loss/len(train_loader), adv_acc=f"{(100.*correct/total):.2f}%")

    return 100. * correct / total

for epoch in range(adv_epochs):
    print(f"\nEpoch {epoch+1}/{adv_epochs}")
    adv_train_acc = adversarial_train_epoch(model, train_loader, optimizer_adv, criterion, epsilon_train, device)

final_adv_accuracy = eval_adversarial(model, test_loader, epsilon=0.1)

print("-" * 30)
print(f"Final Adversarial Test Accuracy: {final_adv_accuracy:.2f}%")
if final_adv_accuracy >= 70.0:
    print("✅ Success! The model meets the 70% robustness requirement.")
else:
    print("❌ The model did not reach 70% accuracy. Consider more epochs or adjusting the LR.")
print("-" * 30)

"""### Visualization

Display the confusion matrix along with some examples of images that the model classified incorrectly. Discuss the performance of the model now compared to before.
"""

cm_adv_after = confusion_matrix_adversarial(model, test_loader, epsilon=0.1)

plot_confusion_matrix(cm_adv_after, title="Confusion Matrix - After Adversarial Training (eps=0.1)")

def show_misclassified_adversarial(model, test_loader, epsilon, num_images=5):
    model.eval()
    found_images = []

    for x, y in test_loader:
        x, y = x.to(device), y.to(device)

        x_adv = fgsm_attack_pixelspace(model, x, y, epsilon)

        with torch.no_grad():
            outputs = model(x_adv)
            preds = outputs.argmax(dim=1)

        misclassified_mask = (preds != y)
        indices = misclassified_mask.nonzero(as_tuple=False).view(-1)

        for idx in indices:
            if len(found_images) >= num_images:
                break

            img_show = denormalize_batch(x_adv[idx].unsqueeze(0), mean, std, device)
            img_show = img_show.squeeze().cpu().permute(1, 2, 0).numpy()

            found_images.append({
                'img': img_show,
                'pred': preds[idx].item(),
                'actual': y[idx].item()
            })

        if len(found_images) >= num_images:
            break

    fig, axes = plt.subplots(1, len(found_images), figsize=(15, 5))
    for i, data in enumerate(found_images):
        axes[i].imshow(data['img'])
        axes[i].set_title(f"Pred: {data['pred']} | Actual: {data['actual']}")
        axes[i].axis('off')
    plt.show()

show_misclassified_adversarial(model, test_loader, epsilon=0.1)

