# -*- coding: utf-8 -*-
"""hw4_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeeNZ1TIOAA8OGHsVONzhQhXOVxpvAUe

#**GAN**

##**Implementation**

**Imports + Seeds + Device**
"""

import os, json, random, math, time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms
from torchvision.utils import make_grid

def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

"""**Extract the dataset**"""

#!mkdir -p /content/flowers102
#!tar -xzf 102flowers.tgz -C /content/flowers102
#!find /content/flowers102 -maxdepth 2 -type d

"""**Paths**"""

DATA_ROOT = Path("/content/flowers102")
IMAGES_ROOT = DATA_ROOT / "jpg"
LABELS_JSON = Path("/content/category_to_images.json")  # אם העלית לשורש /content

print("IMAGES_ROOT exists:", IMAGES_ROOT.exists(), IMAGES_ROOT)
print("LABELS_JSON exists:", LABELS_JSON.exists(), LABELS_JSON)

assert IMAGES_ROOT.exists(), "Images folder not found"
assert LABELS_JSON.exists(), "category_to_images.json not found (upload it to /content)"

"""**Dataset + DataLoader + Real batch preview**"""

class Flowers102FromJson(Dataset):
    def __init__(self, images_root: Path, labels_json: Path, image_size: int = 64):
        assert image_size >= 64, "HW rule: do not resize below 64x64."
        self.images_root = images_root

        with open(labels_json, "r") as f:
            mapping = json.load(f)

        samples = []

        for class_key, img_list in mapping.items():
              class_id = int(class_key)
              for img_rel in img_list:
                  samples.append((img_rel, class_id))

        self.samples = samples

        self.transform = transforms.Compose([
            transforms.Resize((image_size, image_size)),
            transforms.CenterCrop((image_size, image_size)),
            transforms.ToTensor(),
            transforms.Normalize((0.5,)*3, (0.5,)*3),
        ])

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx: int):
        img_rel, class_id = self.samples[idx]
        img_path = self.images_root / img_rel
        if not img_path.exists():
            img_path = self.images_root / Path(img_rel).name

        image = Image.open(img_path).convert("RGB")
        image = self.transform(image)
        return image, class_id, str(img_path)

IMAGE_SIZE = 64
BATCH_SIZE = 64
NUM_WORKERS = 2

dataset = Flowers102FromJson(IMAGES_ROOT, LABELS_JSON, image_size=IMAGE_SIZE)
loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)

print("Dataset size:", len(dataset))

images, _, _ = next(iter(loader))
grid = make_grid(images[:16], nrow=4, normalize=True, value_range=(-1,1))
plt.figure(figsize=(6,6))
plt.axis("off")
plt.title("Real images (first batch)")
plt.imshow(grid.permute(1,2,0))
plt.show()

"""**DCGAN Models (Generator + Discriminator) + init**"""

def weights_init_dcgan(m):
    name = m.__class__.__name__
    if "Conv" in name or "Linear" in name:
        nn.init.normal_(m.weight.data, 0.0, 0.02)
        if getattr(m, "bias", None) is not None and m.bias is not None:
            nn.init.constant_(m.bias.data, 0.0)
    elif "BatchNorm" in name:
        nn.init.normal_(m.weight.data, 1.0, 0.02)
        nn.init.constant_(m.bias.data, 0.0)

class DCGANGenerator(nn.Module):
    def __init__(self, latent_dim: int = 128, base_channels: int = 64, image_channels: int = 3):
        super().__init__()
        self.net = nn.Sequential(
            nn.ConvTranspose2d(latent_dim, base_channels*8, 4, 1, 0, bias=False),  # 4x4
            nn.BatchNorm2d(base_channels*8),
            nn.ReLU(True),

            nn.ConvTranspose2d(base_channels*8, base_channels*4, 4, 2, 1, bias=False),  # 8x8
            nn.BatchNorm2d(base_channels*4),
            nn.ReLU(True),

            nn.ConvTranspose2d(base_channels*4, base_channels*2, 4, 2, 1, bias=False),  # 16x16
            nn.BatchNorm2d(base_channels*2),
            nn.ReLU(True),

            nn.ConvTranspose2d(base_channels*2, base_channels, 4, 2, 1, bias=False),    # 32x32
            nn.BatchNorm2d(base_channels),
            nn.ReLU(True),

            nn.ConvTranspose2d(base_channels, image_channels, 4, 2, 1, bias=False),     # 64x64
            nn.Tanh()  # output in [-1,1]
        )

    def forward(self, z):
        return self.net(z)

class DCGANDiscriminator(nn.Module):
    def __init__(self, base_channels: int = 64, image_channels: int = 3):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(image_channels, base_channels, 4, 2, 1, bias=False),  # 32x32
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(base_channels, base_channels*2, 4, 2, 1, bias=False),  # 16x16
            nn.BatchNorm2d(base_channels*2),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(base_channels*2, base_channels*4, 4, 2, 1, bias=False),  # 8x8
            nn.BatchNorm2d(base_channels*4),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(base_channels*4, base_channels*8, 4, 2, 1, bias=False),  # 4x4
            nn.BatchNorm2d(base_channels*8),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(base_channels*8, 1, 4, 1, 0, bias=False)  # (B,1,1,1)
        )

    def forward(self, x):
        logits = self.net(x)
        return logits.view(x.size(0))  # (B,)

LATENT_DIM = 128
G = DCGANGenerator(latent_dim=LATENT_DIM, base_channels=64).to(device)
D = DCGANDiscriminator(base_channels=64).to(device)

G.apply(weights_init_dcgan)
D.apply(weights_init_dcgan)

print("G params:", sum(p.numel() for p in G.parameters()))
print("D params:", sum(p.numel() for p in D.parameters()))

"""**Loss + Optimizers + Fixed Noise (for consistent sampling)**

"""

criterion = nn.BCEWithLogitsLoss()

lr = 2e-4
beta1, beta2 = 0.5, 0.999

opt_G = optim.Adam(G.parameters(), lr=lr, betas=(beta1, beta2))
opt_D = optim.Adam(D.parameters(), lr=lr, betas=(beta1, beta2))

fixed_noise = torch.randn(32, LATENT_DIM, 1, 1, device=device)

print("Ready. fixed_noise:", fixed_noise.shape, fixed_noise.device)

"""**Training loop**"""

def show_generated(generator, noise, title="Generated samples"):
    generator.eval()
    with torch.no_grad():
        fake = generator(noise).detach().cpu()
    generator.train()
    grid = make_grid(fake, nrow=8, normalize=True, value_range=(-1,1))
    plt.figure(figsize=(10,5))
    plt.axis("off")
    plt.title(title)
    plt.imshow(grid.permute(1,2,0))
    plt.show()

def train_dcgan(generator, discriminator, dataloader, opt_g, opt_d, criterion,
                latent_dim=128, num_epochs=10, log_every=200):
    g_losses, d_losses = [], []
    step = 0

    generator.train()
    discriminator.train()

    for epoch in range(num_epochs):
        for real_images, _, _ in dataloader:
            real_images = real_images.to(device)
            batch_size = real_images.size(0)

            # -------------------------
            # 1) Train Discriminator
            # -------------------------
            opt_d.zero_grad(set_to_none=True)

            real_targets = torch.full((batch_size,), 0.9, device=device)
            fake_targets = torch.zeros(batch_size, device=device)

            real_logits = discriminator(real_images)
            loss_d_real = criterion(real_logits, real_targets)

            noise = torch.randn(batch_size, latent_dim, 1, 1, device=device)
            fake_images = generator(noise).detach()
            fake_logits = discriminator(fake_images)
            loss_d_fake = criterion(fake_logits, fake_targets)

            loss_d = loss_d_real + loss_d_fake
            loss_d.backward()
            opt_d.step()

            # -------------------------
            # 2) Train Generator
            # -------------------------
            opt_g.zero_grad(set_to_none=True)

            noise = torch.randn(batch_size, latent_dim, 1, 1, device=device)
            generated_images = generator(noise)
            gen_logits = discriminator(generated_images)

            loss_g = criterion(gen_logits, real_targets)  # non-saturating
            loss_g.backward()
            opt_g.step()

            d_losses.append(loss_d.item())
            g_losses.append(loss_g.item())

            if step % log_every == 0:
                print(f"epoch {epoch+1}/{num_epochs} | step {step} | loss_D={loss_d.item():.4f} | loss_G={loss_g.item():.4f}")
            step += 1

        show_generated(generator, fixed_noise, title=f"Generated after epoch {epoch+1}")

    return g_losses, d_losses

"""##**Train**"""

NUM_EPOCHS = 50
g_losses, d_losses = train_dcgan(G, D, loader, opt_G, opt_D, criterion,
                                 latent_dim=LATENT_DIM, num_epochs=NUM_EPOCHS, log_every=200)

print("D first 10:", [round(x,3) for x in d_losses[:10]])
print("G first 10:", [round(x,3) for x in g_losses[:10]])

print("D last 10 :", [round(x,3) for x in d_losses[-10:]])
print("G last 10 :", [round(x,3) for x in g_losses[-10:]])

print("D mean last 200:", round(float(np.mean(d_losses[-200:])), 3))
print("G mean last 200:", round(float(np.mean(g_losses[-200:])), 3))

"""**Plot loss as a function of training steps (D and G)**

"""

plt.figure(figsize=(10,4))
plt.plot(d_losses, label="Discriminator loss")
plt.plot(g_losses, label="Generator loss")
plt.xlabel("Training step")
plt.ylabel("Loss")
plt.title("GAN Loss vs. Training Steps")
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()

"""##**Generate**

**Part A — Generate images**
"""

G.eval()
z = torch.randn(16, LATENT_DIM, 1, 1, device=device)
with torch.no_grad():
    fake = G(z).detach().cpu()
G.train()

grid = make_grid(fake, nrow=4, normalize=True, value_range=(-1,1))
plt.figure(figsize=(6,6))
plt.axis("off")
plt.title("16 generated images (random z)")
plt.imshow(grid.permute(1,2,0))
plt.show()

"""**Part B1 — Generate a pool of images (keeping their z vectors)**

"""

POOL_SIZE = 300

G.eval()
z_pool = torch.randn(POOL_SIZE, LATENT_DIM, 1, 1, device=device)
with torch.no_grad():
    fake_pool = G(z_pool).detach().cpu()
G.train()

z_pool = z_pool.detach().cpu()

print("fake_pool:", fake_pool.shape)  # (POOL_SIZE, 3, 64, 64)
print("z_pool   :", z_pool.shape)     # (POOL_SIZE, LATENT_DIM, 1, 1)


def show_pool_with_indices(images, n=36):
    n = min(n, len(images))
    cols = int(math.sqrt(n))
    rows = math.ceil(n / cols)
    plt.figure(figsize=(2.2*cols, 2.2*rows))
    for i in range(n):
        ax = plt.subplot(rows, cols, i+1)
        img = (images[i] * 0.5 + 0.5).clamp(0,1)  # [-1,1] -> [0,1]
        ax.imshow(img.permute(1,2,0))
        ax.set_title(str(i), fontsize=10)
        ax.axis("off")
    plt.tight_layout()
    plt.show()

show_pool_with_indices(fake_pool, n=36)

"""**Part B3 — Choose pairs of images + plot their z vectors**


"""

def z_flat(z):  # (LATENT_DIM,1,1) -> (LATENT_DIM,)
    return z.view(-1)

# EDIT THESE after you look at the indexed pool:
similar_pairs = [(0, 5), (2, 18), (7, 11)]
dissimilar_pairs = [(1, 9), (3, 20), (6, 15)]

def show_pair(i, j, title):
    img_i = (fake_pool[i] * 0.5 + 0.5).clamp(0,1)
    img_j = (fake_pool[j] * 0.5 + 0.5).clamp(0,1)

    zi = z_flat(z_pool[i])
    zj = z_flat(z_pool[j])

    l2 = torch.norm(zi - zj, p=2).item()
    cos = torch.nn.functional.cosine_similarity(zi.unsqueeze(0), zj.unsqueeze(0)).item()

    plt.figure(figsize=(7,3))
    plt.subplot(1,2,1); plt.imshow(img_i.permute(1,2,0)); plt.axis("off"); plt.title(f"idx {i}")
    plt.subplot(1,2,2); plt.imshow(img_j.permute(1,2,0)); plt.axis("off"); plt.title(f"idx {j}")
    plt.suptitle(f"{title} | L2(z)={l2:.2f} | cos(z)={cos:.2f}")
    plt.tight_layout()
    plt.show()

def plot_z_pairs(pairs, title):
    plt.figure(figsize=(12,4))
    for k, (i, j) in enumerate(pairs, 1):
        zi = z_flat(z_pool[i]).numpy()
        zj = z_flat(z_pool[j]).numpy()
        plt.plot(zi, label=f"pair{k}: idx{i} (solid)")
        plt.plot(zj, linestyle="--", label=f"pair{k}: idx{j} (dashed)")
    plt.title(title)
    plt.xlabel("latent dimension")
    plt.ylabel("z value")
    plt.legend(ncol=3, fontsize=9)
    plt.grid(True, alpha=0.2)
    plt.show()

print("=== Similar pairs ===")
for i, j in similar_pairs:
    show_pair(i, j, "SIMILAR")
plot_z_pairs(similar_pairs, "z vectors — Similar pairs (solid vs dashed)")

print("=== Dissimilar pairs ===")
for i, j in dissimilar_pairs:
    show_pair(i, j, "DISSIMILAR")
plot_z_pairs(dissimilar_pairs, "z vectors — Dissimilar pairs (solid vs dashed)")

"""**Clear visualization — heatmap of selected z vectors**

"""

selected_indices = [i for pair in similar_pairs for i in pair] + [i for pair in dissimilar_pairs for i in pair]
selected_indices = list(dict.fromkeys(selected_indices))  # unique, keep order

Z = np.stack([z_pool[i].view(-1).numpy() for i in selected_indices], axis=0)

plt.figure(figsize=(12, 3))
plt.imshow(Z, aspect="auto", interpolation="nearest")
plt.colorbar(label="z value")
plt.yticks(range(len(selected_indices)), [f"idx {i}" for i in selected_indices])
plt.xlabel("latent dimension")
plt.title("Selected z vectors (rows) as heatmap")
plt.show()

"""##**Saving Model Weights**"""

import pickle

ckpt = {
    "G_state_dict": G.state_dict(),
    "D_state_dict": D.state_dict(),
    "LATENT_DIM": LATENT_DIM,
    "IMAGE_SIZE": 64,
    "MODEL_TYPE": "GAN",
}

with open("hw4_model_gpu_backup.pkl", "wb") as f:
    pickle.dump(ckpt, f)

print("Saved hw4_model_gpu_backup.pkl")

from google.colab import files
files.download("hw4_model_gpu_backup.pkl")